// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp9eE48lcfqSIdfsyaH57t0qgqbVziroA',
    appId: '1:607127368219:web:62ce3f1164558657c6febe',
    messagingSenderId: '607127368219',
    projectId: 'resqrun-1f0dd',
    authDomain: 'resqrun-1f0dd.firebaseapp.com',
    storageBucket: 'resqrun-1f0dd.appspot.com',
    measurementId: 'G-L86GLL599S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLN_3m0bKvdM1k5mKCUU_LmN1-ZZkTnGY',
    appId: '1:607127368219:android:42e2a5ec1291010ac6febe',
    messagingSenderId: '607127368219',
    projectId: 'resqrun-1f0dd',
    storageBucket: 'resqrun-1f0dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYfe-8n4oNfjParZx6BjH_vxBYmN6VCrc',
    appId: '1:607127368219:ios:c2fe21888e922a87c6febe',
    messagingSenderId: '607127368219',
    projectId: 'resqrun-1f0dd',
    storageBucket: 'resqrun-1f0dd.appspot.com',
    iosBundleId: 'com.example.resqrun',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYfe-8n4oNfjParZx6BjH_vxBYmN6VCrc',
    appId: '1:607127368219:ios:c2fe21888e922a87c6febe',
    messagingSenderId: '607127368219',
    projectId: 'resqrun-1f0dd',
    storageBucket: 'resqrun-1f0dd.appspot.com',
    iosBundleId: 'com.example.resqrun',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp9eE48lcfqSIdfsyaH57t0qgqbVziroA',
    appId: '1:607127368219:web:3576beefb6fe7cebc6febe',
    messagingSenderId: '607127368219',
    projectId: 'resqrun-1f0dd',
    authDomain: 'resqrun-1f0dd.firebaseapp.com',
    storageBucket: 'resqrun-1f0dd.appspot.com',
    measurementId: 'G-E37MLQN7CQ',
  );
}
